[project]
name = "py-duck"
version = "0.1.0"
description = "Hello world"
readme = "README.md"
authors = [
    { name = "Tom Conder", email = "tom@itstom.co" }
]
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.3.2",
    "pylint>=3.3.7",
    "ruff>=0.12.3",
]
